spring.application.name=searcher
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/github_db
spring.datasource.username=root
spring.datasource.password=Sakshika2002@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# No API key needed for GitHub public API
# But adding a token avoids rate limits (60 req/hr without, 5000 with)
github.token=